[project]
name = "cloud-pipelines-backend"
version = "0.1.0"
description = "Backend for Cloud Pipelines"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cloud-pipelines>=0.23.2.4",
    "fastapi[standard]>=0.115.12",
    "kubernetes>=33.1.0",
    "requests<2.32.0",
    "sqlalchemy>=2.0.41",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "pytest>=8.4.2",
]
huggingface = [
    "huggingface-hub[oauth]>=0.35.3",
]

[tool.setuptools.packages.find]
include = ["cloud_pipelines_backend*"]
namespaces = true

[tool.black]
# Usage: uv run black .
#
# TODO: Line length per Google Python Style Guide:
# https://google.github.io/styleguide/pyguide.html#32-line-length
# line-length = 80
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
)/
'''
